/**
 * rebalance.ts
 * Pure functions for auto-balancing sector views and computing implied
 * tracking error.  No React imports — safe to unit-test in isolation.
 *
 * Auto-balance rule (Mesa de Dinero, per-region constraint):
 *   Σ magnitude_i = 0   for all sectors in a region
 *
 * Algorithm (when the user edits sector `changedId` to `newValue`):
 *  1. Set changedId = newValue in the result.
 *  2. Compute required delta = −newValue − currentSumOfOthers
 *     (the amount that must be redistributed to make sum = 0).
 *  3. Distribute delta equally among "free" sectors (those not yet clamped).
 *  4. If a sector hits [min, max], clamp it and carry the residual forward.
 *  5. Repeat up to 5 rounds until |residual| < 0.01.
 */

import { teFactor } from '@/data/mesaDinero'

// ─── Sector auto-balance ──────────────────────────────────────────────────────

/**
 * Returns an updated views map after changing `changedId` to `newValue`,
 * distributing the balancing residual equally across the other sectors in
 * the same region, clamping each to [min, max] and iterating.
 */
export function rebalanceRegion(
  views:     Record<string, number>,
  changedId: string,
  newValue:  number,
  regionIds: string[],
  min = -5,
  max =  5,
): Record<string, number> {
  const result  = { ...views, [changedId]: newValue }
  const others  = regionIds.filter(id => id !== changedId)

  if (!others.length) return result

  // How much do the others currently sum to?
  const currentOthersSum = others.reduce((s, id) => s + (result[id] ?? 0), 0)
  // They must sum to exactly −newValue so the region total is 0.
  let residual = -newValue - currentOthersSum

  if (Math.abs(residual) < 0.001) return result

  // Distribute iteratively (up to 5 rounds) so that clamped sectors pass
  // their share on to the remaining free sectors.
  for (let round = 0; round < 5 && Math.abs(residual) > 0.01; round++) {
    const free = others.filter(id => {
      const v = result[id] ?? 0
      return residual > 0 ? v < max : v > min
    })
    if (!free.length) break

    const share = residual / free.length

    for (const id of free) {
      const prev    = result[id] ?? 0
      const desired = prev + share
      const clamped = Math.max(min, Math.min(max, desired))
      residual     -= clamped - prev
      // Round to nearest 0.5 pp for clean display
      result[id]    = Math.round(clamped * 2) / 2
    }
  }

  return result
}

/**
 * Force-balances a region without changing the user's largest active bets.
 * Adjusts the sectors with the smallest absolute values first, spreading the
 * correction among them until the region sums to 0.
 *
 * Used by the "Auto-balancear" button.
 */
export function forceBalance(
  views:     Record<string, number>,
  regionIds: string[],
  min = -5,
  max =  5,
): Record<string, number> {
  const sum = regionIds.reduce((s, id) => s + (views[id] ?? 0), 0)
  if (Math.abs(sum) < 0.01) return views

  // Sort by |magnitude| ascending — adjust the smallest bets first to preserve
  // the intent of the largest conviction positions.
  const sorted = [...regionIds].sort(
    (a, b) => Math.abs(views[a] ?? 0) - Math.abs(views[b] ?? 0),
  )

  // Apply the correction by "editing" the smallest sector and running the
  // regular rebalance across the others.  Repeat until balanced.
  let result = { ...views }
  let maxIter = 10
  while (Math.abs(regionIds.reduce((s, id) => s + (result[id] ?? 0), 0)) > 0.01 && maxIter-- > 0) {
    const pivot = sorted[0]
    result = rebalanceRegion(result, pivot, result[pivot] ?? 0, regionIds, min, max)

    // If rounding left a tiny residual, nudge the pivot
    const residual = regionIds.reduce((s, id) => s + (result[id] ?? 0), 0)
    if (Math.abs(residual) > 0.01) {
      const pivotVal = Math.round((result[pivot] - residual) * 2) / 2
      result[pivot]  = Math.max(min, Math.min(max, pivotVal))
    }
    break
  }

  return result
}

// ─── Implied Tracking Error ───────────────────────────────────────────────────

/**
 * Computes implied TE as the quadratic sum of individual active-weight
 * contributions, each scaled by a per-asset-class TE factor.
 *
 *   TE_implied = sqrt( Σ (factor_i × |magnitude_i|)² )   (% annualized)
 *
 * The factors in mesaDinero.ts represent the TE generated by 1 pp of active
 * weight in each asset class (residual volatility per unit active weight).
 */
export function computeImpliedTE(views: Record<string, number>): number {
  const sumOfSquares = Object.entries(views).reduce((s, [id, mag]) => {
    const f = teFactor[id] ?? 0.15
    return s + Math.pow(f * Math.abs(mag), 2)
  }, 0)
  return Math.sqrt(sumOfSquares)
}

// ─── Region balance check ─────────────────────────────────────────────────────

/** Returns the sum of magnitudes for a region (should be 0 when balanced). */
export function regionSum(
  views:     Record<string, number>,
  regionIds: string[],
): number {
  return regionIds.reduce((s, id) => s + (views[id] ?? 0), 0)
}

/** True if every region in `regionGroups` sums to 0. */
export function allRegionsBalanced(
  views:        Record<string, number>,
  regionGroups: string[][],
): boolean {
  return regionGroups.every(ids => Math.abs(regionSum(views, ids)) < 0.01)
}
